**Hypothesis testing**

**1.A machine is producing perfume bottels with the long term average of 150ml and the standerd deviation is 2ml, four bottels were picked & the average volume was found to be 149ml.Has the average volume was min of 150? test with 95% confidence level.**

**step1:

H0:mean value>=500 (no acttion)
H1:mean value<500 (action)
step2:

alpha=0.05
step3:

1 sample Ztst
step4:**

In [7]:
from scipy import stats
import numpy as np

In [11]:
ztest=(149-150)/(2/np.sqrt(4))
ztest

-1.0

In [13]:
#p value
stats.norm.cdf(-1.0)

0.15865525393145707

**Accept left tail rejection(H0)**

**2.The mean responce time for a random sample 30 pizza delivers is 32min.The population standerd deviatioon is 10.The pizza delivery service is wants to perform hypothesis test with 0.05 level of significance, to determine service goal of 30min or less is being achived**

H0:mean value<=30(no action)
H!:mean value>30 (action)
alpha=0.05
1 sample ztezt

In [20]:
ztest=(32-30)/(10/np.sqrt(30))
ztest

1.0954451150103321

In [24]:
# p vaue
1-stats.norm.cdf(1.0954451150103321)

0.13666083914614902

***alpha<p vaue
accept right tail rejection(H0)***

**3.Assume that a 30 milk cortan provides a sample mean of 505ml.The population of the standerd deviation is 10ml.Perform hypothesis test 0.03 level of significance the population mean of 500 ml and helph to determine wether filling process shoud continuing or stopped and corrected**

H0:mean value==500ml(no action)
H1:mean value!=500ml(action)
aplpha=0.03
two tail z test

In [27]:
ztest=(505-500)/(10/np.sqrt(30))
ztest

2.7386127875258306

In [35]:
p_value=2*stats.norm.sf(2.7386127875258306)
p_value

0.00616989932054416

***p_value<alpha
reject H0***

**statistical test**

**CASE STUDY1: The length of 25 sample of a fabric are token at random historical mean and standerd deviation are 150cm & 5.5 cm respectively company managers wants to test if the current is equal to the historic mean.Assum alpha to be 0.05.**

step1: Formulation of H0 and H1
    H0:mean value==500ml(no action)
    H1:mean value!=500ml(action)
step2:select the level of significance
    alpha=0.05
step3:check the normality

In [12]:
from scipy import stats
import pandas as pd
df1=pd.read_excel("C:\\Users\\Asus\\OneDrive\\Desktop\\Fabric data.xlsx")
df1.head()

   Fabric_length
0          151.2
1          160.3
2          147.5
3          149.2
4          159.2

In [14]:
# checking the normality
df1['Fabric_length'].skew()

0.29650632012590666

In [16]:
df1['Fabric_length'].mean()

155.064

step4: 1 sample ztest with two tail rejection

In [26]:
import numpy as np
ztest=(155.064-150)/(5.5/np.sqrt(25))
ztest

4.603636363636356

In [28]:
p_value=2*stats.norm.sf(4.603636363636356)
p_value

4.151771321155016e-06

In [30]:
stats.shapiro(df1['Fabric_length'])

ShapiroResult(statistic=0.9397523999214172, pvalue=0.1460934281349182)

**CASE STUDY2: The mean daimeter of the bolt manufactured should be 10mm tobe able to fit  in to nut,20 samples are token at the random from production line by a quality inspector conduct a test to check with 90% confedence that the mean is not diffrence from the specification value**

step1:
    H0:mean value=10 (no action)
    H1:mean value!=10 (action)
step2:
    alpha=0.1
step3:

In [38]:
df2=pd.read_excel('C:\\Users\\Asus\\OneDrive\\Desktop\\Bolt diameter.xlsx')
df2.head()

   Diameter
0     11.27
1     12.06
2     12.15
3      9.89
4     10.82

step4: select the statistical test and calculate the p value

In [40]:
df2['Diameter'].skew()

0.380916607218941

In [44]:
from scipy import stats
ttest=stats.ttest_1samp(df2['Diameter'],popmean=10,alternative='two-sided')
ttest

TtestResult(statistic=4.1146847709314756, pvalue=0.0005896412896356807, df=19)

***pvalue<aplha
Reaject null hypothesis(H0)***

**CASE STUDY3:A machine is producting perfume bottels with the long term average of 150ml ad the standerd deviation is 2ml,four bottels were picked and the average valume was found to be 149ml.has the average volume min of 150ml? test with 95% confedence level.**

step1:Formation of H0 and H1
    H0:mean value>=150ml (no action)
    H1:mean value<150ml (action)
step2:
    aplha=0.05
step3:
    1 sample ztest left tail rejection

In [52]:
ztest=(149-150)/(2/np.sqrt(4))
ztest

-1.0

In [54]:
#calculating p value
stats.norm.cdf(-1.0)

0.15865525393145707

***pvalue>aplha
Accept null hypothesis(H0)***

**CASE STUDY4: The mean responce time of a random sample 30 pizza delivery is 32 minuts. The population standerd deviation is 10 the pizza delivary service wants to perform hypothesis test with 0.05 level of significance to determine service goal of 30 min or less is being achived.**

step1:
    H0:mean value<=30 (no action)
    H!:mean value>30 (action)
step2:
    alpha=0.05
step3:normalization
step4:

In [5]:
import numpy as np
ztest=(32-30)/(10/np.sqrt(30))
ztest

1.0954451150103321

In [15]:
# p value
from scipy import stats
1-stats.norm.cdf(1.0954451150103321)

0.13666083914614902

***p value>alphs
Accept null hypothesis(H0)***

**ANNOVA TEST**

**A financial analyst at a finacial institute wants to evalvate a recent creadit card promotion. After this promotion ,500 card holders were randomaly selected.half recived and ad promoting a full waiver of intrest rate on purchase made over the next thre months and half recived a standerd christmas advertisement.Did ad promoting ful intrest rate waiver,increase purchase**

step1:
    H0:avg of purchase made by FIW <= Avg purchase made by sc(no action)
    H1:avg of purchase made by FIW > Avg purchase made by sc(no action
step2:
    alpha=0.05
step3: check the normality

In [4]:
from scipy  import stats
import pandas as pd

In [8]:
df3=pd.read_excel('C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\Promotion.xlsx')
df3.head()

   InterestRateWaiver  StandardPromotion
0             1989.10            1272.25
1             1808.38            1250.38
2             1153.75            1474.78
3             1745.64            2064.89
4             1008.24            2030.87

In [16]:
df3['InterestRateWaiver'].skew()

-0.186848927819777

In [18]:
df3['StandardPromotion'].skew()

0.1556560407787534

In [20]:
# Annova test
annova_test=stats.f_oneway(df3['InterestRateWaiver'],df3['StandardPromotion'])
annova_test

F_onewayResult(statistic=5.109521918142664, pvalue=0.02422584468584416)

***p_value<alpha
Reject null hyphothesis(H0)***

**1 PROPOTION TEST**

**CASE STUDY5: The people carry out a poll to find the acceptability of a new footboll coach.It was a decided that if the support rate for the coacch for the entire population was trully less then 90% the coach would be fired.2000 people pparticipeted and 436 people supported the new coach.Connduct a test iif the new coachbshould be fired with the 95% confedence.**

step1:
    H0:coach not be fired(no action)
    H1:coach to be fired(action)
step2:
    alpha=0.05
step3:
    1 proption test

In [24]:
binome_test=stats.binomtest(496,2000,0.95)
binome_test

BinomTestResult(k=496, n=2000, alternative='two-sided', statistic=0.248, pvalue=0.0)

***p < alpha
Reject null hyphothesis***

**CHI-SQUARE TEST**

**CASE STUDY6:Jonny Talkers soft drinks division sales manager has been planning to launch  a new slaes incetive program from theire sales executive.The sales executive felt the adults(>40 yrs) won't buy childerns will and hence requested sales manager no to launch a program. Analyse the data and determine whether there is a avidence at 5% significance lebvel to support the hypothesis**

step1:
    H0:proportion for adults = proportion for for childerns(no action)
    H1:proportion for adults != proportion for for childerns(action)
step2:
    alpha=0.05
step3:
    chi-square test

In [36]:
df5=pd.read_excel('C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\JohnyTalkers.xlsx')
df5.head()

   Person            Drinks
0  Adults  Did Not Purchase
1  Adults  Did Not Purchase
2  Adults  Did Not Purchase
3  Adults  Did Not Purchase
4  Adults  Did Not Purchase

In [38]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1220 entries, 0 to 1219
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Person  1220 non-null   object
 1   Drinks  1220 non-null   object
dtypes: object(2)
memory usage: 19.2+ KB

In [44]:
df5['Person'].value_counts()

Children    740
Adults      480
Name: Person, dtype: int64

In [46]:
df5['Drinks'].value_counts()

Did Not Purchase    1010
Purchased            210
Name: Drinks, dtype: int64

In [50]:
pd.crosstab(df5['Person'],df5['Drinks'],margins=True)

Drinks    Did Not Purchase  Purchased   All
Person
Adults                 422         58   480
Children               588        152   740
All                   1010        210  1220