In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\Advertising.csv")
df.head()

       TV  radio  newspaper  sales
0  230100  37800      69200  22100
1   44500  39300      45100  10400
2   17200  45900      69300   9300
3  151500  41300      58500  18500
4  180800  10800      58400  12900

In [9]:
X=df.drop(columns=['sales'])
y=df['sales']

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

# Modeling Polynomial Regresssion

- Incresing to higher degree of input variables applying lenear regression

In [138]:
X=df[['TV','radio','newspaper']]
y=df['sales']

In [140]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter=PolynomialFeatures(degree=2,include_bias=False)
polynomial_converter.fit_transform(X_train)

array([[3.95000e+04, 4.11000e+04, 5.80000e+03, ..., 1.68921e+09,
        2.38380e+08, 3.36400e+07],
       [1.20200e+05, 1.96000e+04, 1.16000e+04, ..., 3.84160e+08,
        2.27360e+08, 1.34560e+08],
       [1.42900e+05, 2.93000e+04, 1.26000e+04, ..., 8.58490e+08,
        3.69180e+08, 1.58760e+08],
       ...,
       [1.95400e+05, 4.77000e+04, 5.29000e+04, ..., 2.27529e+09,
        2.52333e+09, 2.79841e+09],
       [8.72000e+04, 1.18000e+04, 2.59000e+04, ..., 1.39240e+08,
        3.05620e+08, 6.70810e+08],
       [1.99800e+05, 2.60000e+03, 2.12000e+04, ..., 6.76000e+06,
        5.51200e+07, 4.49440e+08]])

In [142]:
X_train_poly=pd.DataFrame(polynomial_converter.fit_transform(X_train))

In [144]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [146]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train_poly,y_train)

LinearRegression()

In [148]:
print("Intercept:",model.intercept_)
print("coeficents:",model.coef_)

Intercept: 5118.899323780606
coeficents: [ 4.97361575e-02  3.96785738e-02  2.33407905e-04 -1.03800633e-07
  1.03104853e-06 -8.95964702e-09  1.18811903e-07 -2.85278061e-08
  4.59336554e-08]

In [150]:
ypred_train=model.predict(X_train_poly)

In [152]:
from sklearn.metrics import r2_score
print("The r2 score of X_train",r2_score(y_train,ypred_train))
print("The cross val score:",cross_val_score(model,X_train_poly,y_train,cv=5).mean())

The r2 score of X_train 0.9893215378017587
The cross val score: 0.9865047119218879

In [164]:
X_test_poly=pd.DataFrame(polynomial_converter.transform(X_test))
ypred_test=model.predict(X_test_poly)

In [166]:
from sklearn.metrics import r2_score
print("The r2 score of X_test",r2_score(y_test,ypred_test))
print("The cross val score:",cross_val_score(model,X_test_poly,y_test,cv=5).mean())

The r2 score of X_test 0.9769706288994677
The cross val score: 0.9564682355882791

# Final Polynomial Model with Best Degree

In [94]:
final_poly_converter=PolynomialFeatures(degree=3,include_bias=False)
X_train_poly=pd.DataFrame(final_poly_converter.fit_transform(X_train))

In [116]:
final_model=LinearRegression()
final_model.fit(X_train_poly,y_train)
# prediction and evalation
train_pred=final_model.predict(X_train_poly)
print("The r2 score",final_model.score(X_train_poly,y_train))
from sklearn.model_selection import cross_val_score
print("The cross val score",cross_val_score(final_model,X_train_poly,y_train,cv=5).mean())

The r2 score 0.9943125661466566
The cross val score 0.9889706034017125

In [174]:
X_test_poly=pd.DataFrame(final_poly_converter.transform(X_test))
pred_test=final_model.predict(X_test_ploy)
print("The r2 score",final_model.score(X_test_ploy,y_test))

The r2 score 0.9834260730735231

# Prediction on new data

**Our next campaign will have toatal spend on 149k on TV,22k on radio and 12k on news paper ads..how many units colud we expect to sell as
a result of this?**

In [172]:
test_df=pd.DataFrame({'TV':[149000],'radio':[22000],'newspaper':[12000]})
test_df

       TV  radio  newspaper
0  149000  22000      12000

In [176]:
transformed_data=final_poly_converter.transform(test_df)

In [180]:
print("Expected sales for given spend:",final_model.predict(transformed_data)[0])

Expected sales for given spend: 14538.280976340346